"""Hand-written use-case flows. Every step names a real class; analyze.py verifies each hop against the graph
(direct edge, short path, or 'no static link' meaning the hop happens over HTTP, config or reflection)."""

E = "emissary."

USE_CASES = [
    {
        "id": "standalone",
        "title": "Process files on a single node",
        "who": "Operator",
        "summary": "Start one node, drop files in an input directory, and get processed output. This is the "
                   "default ./emissary server -m standalone path and the main thing Emissary does.",
        "steps": [
            (E + "Emissary", "The ./emissary script runs this picocli dispatcher."),
            (E + "command.ServerCommand", "`server -m standalone` picks the STANDALONE config flavor."),
            (E + "server.EmissaryServer", "Starts embedded Jetty and registers the REST and web UI resources."),
            (E + "server.InitializeContext", "Servlet listener: creates the AgentPool and MoveSpool, then starts places."),
            (E + "admin.Startup", "Reads places.cfg (plus flavor) and bootstraps processing places, then pickup places."),
            (E + "admin.PlaceStarter", "Instantiates each place class named in ClassNameInventory."),
            (E + "pickup.file.FilePickUpPlace", "Polls the InputData directory for new files."),
            (E + "pickup.PickUpPlace", "Wraps each file as a BaseDataObject with form UNKNOWN and hands it to an agent."),
            (E + "pool.AgentPool", "Lends an idle agent (blocks when all are busy)."),
            (E + "core.HDMobileAgent", "Runs the itinerary loop for the payload and any attachments it sprouts."),
            (E + "directory.DirectoryPlace", "Answers 'which place handles this form at this stage, cheapest first?'"),
            (E + "place.ServiceProviderPlace", "Each chosen place runs process() and changes the payload's forms."),
            (E + "output.DropOffPlace", "IO stage: the whole payload family is dropped off together."),
            (E + "output.filter.DataFilter", "Default output filter writes the processed bytes to OutputData."),
        ],
        "seeds": ["command.ServerCommand", "pickup.file.FilePickUpPlace", "core.HDMobileAgent", "output.DropOffPlace"],
        "configs": ["places-STANDALONE.cfg", "places.cfg", "emissary.pickup.file.FilePickUpPlace-STANDALONE.cfg",
                    "AgentPool.cfg", "DropOffPlace.cfg"],
    },
    {
        "id": "cluster",
        "title": "Spread work across a cluster",
        "who": "Operator",
        "summary": "A feeder process scans input and hands out work bundles; every node pulls bundles and runs the "
                   "full itinerary locally. Agents do not move between nodes in the current code.",
        "steps": [
            (E + "command.FeedCommand", "`./emissary feed` starts a WorkSpace (class selectable with -w)."),
            (E + "pickup.WorkSpace", "Scans input directories and packs file names into bundles."),
            (E + "pickup.WorkBundle", "A batch of file paths plus case metadata, sent as XML."),
            (E + "server.mvc.internal.WorkSpaceClientOpenWorkSpaceAction", "Node endpoint: the feeder announces itself."),
            (E + "pickup.file.FilePickUpClient", "Each node's pickup client pulls bundles from the feeder."),
            (E + "server.mvc.adapters.WorkSpaceAdapter", "HTTP adapter for take / complete calls to the feeder."),
            (E + "server.mvc.internal.WorkSpaceClientSpaceTakeAction", "Feeder endpoint that serves the next bundle."),
            (E + "pickup.PickUpPlace", "Files in the bundle are processed exactly as in standalone mode."),
            (E + "server.mvc.internal.WorkBundleCompletedAction", "Node reports the bundle done so the feeder can track it."),
        ],
        "seeds": ["command.FeedCommand", "pickup.WorkSpace", "pickup.file.FilePickUpClient"],
        "configs": ["places-CLUSTER.cfg", "emissary.pickup.file.FilePickUpClient-CLUSTER.cfg", "node.cfg", "peer.cfg"],
    },
    {
        "id": "peers",
        "title": "Discover peers and keep the directory",
        "who": "Runtime",
        "summary": "Nodes find each other from peer.cfg, heartbeat, and share directory state. By default each "
                   "node keeps only its own places, which is why cross-node routing is effectively off.",
        "steps": [
            (E + "directory.EmissaryNode", "Node identity (host, port, mode) from node*.cfg."),
            (E + "directory.DirectoryPlace", "Holds the routing table of DirectoryEntry keys for this node."),
            (E + "directory.HeartbeatManager", "Periodically pings peers and marks them up or down."),
            (E + "server.mvc.internal.HeartbeatAction", "Endpoint receiving a peer's heartbeat."),
            (E + "server.mvc.internal.RegisterPeerAction", "Endpoint a new peer calls to join."),
            (E + "server.mvc.adapters.DirectoryAdapter", "Client side of directory calls; disableAddPlaces=true by default."),
            (E + "directory.KeyManipulator", "Parses FORM.SERVICE.STAGE.URL$COST keys."),
        ],
        "seeds": ["directory.DirectoryPlace", "directory.HeartbeatManager", "directory.EmissaryNode"],
        "configs": ["peer.cfg", "node.cfg", "DirectoryPlace.cfg"],
    },
    {
        "id": "operate",
        "title": "Inspect and control a running node",
        "who": "Operator",
        "summary": "CLI commands and the REST API expose agents, the pool, peers, config and health, and can "
                   "pause, refresh or shut a node down.",
        "steps": [
            (E + "command.AgentsCommand", "`./emissary agents` polls agent status (MonitorCommand base)."),
            (E + "command.MonitorCommand", "Shared polling loop for agents / pool."),
            (E + "client.EmissaryClient", "httpclient5 wrapper used by every CLI command."),
            (E + "server.api.Agents", "GET /api/agents and /api/cluster/agents."),
            (E + "core.Namespace", "Endpoints look agents and places up in the JVM-wide registry."),
            (E + "server.api.Pool", "GET /api/pool."),
            (E + "server.api.Pause", "Pause / unpause pickup."),
            (E + "server.api.Shutdown", "Graceful shutdown."),
            (E + "server.api.HealthCheckAction", "GET /api/health, backed by core.AgentPoolHealthCheck."),
        ],
        "seeds": ["command.AgentsCommand", "command.PoolCommand", "command.PeersCommand", "command.ConfigCommand",
                  "server.api.Agents", "server.api.Pool", "server.api.Peers", "server.api.Places"],
        "configs": ["jetty-users.properties"],
    },
    {
        "id": "custom-place",
        "title": "Write and test a custom place",
        "who": "Developer",
        "summary": "The base framework 'does almost nothing'; users extend ServiceProviderPlace, give it a .cfg with "
                   "its routing key, list it in places.cfg, and test it with the published test-jar harness.",
        "steps": [
            (E + "place.ServiceProviderPlace", "Extend it and override process(d) or processHeavyDuty(d)."),
            (E + "config.ServiceConfigGuide", "Reads the place's .cfg: SERVICE_KEY or SERVICE_NAME/TYPE/PROXY/COST."),
            (E + "directory.DirectoryEntry", "The place registers one entry per key with the directory."),
            (E + "place.sample.ToUpperPlace", "Smallest working example (LOWER_CASE to UPPER_CASE)."),
            (E + "place.sample.TemplatePlace", "Skeleton to copy."),
            (E + "core.IBaseDataObject", "The payload API a place reads and edits."),
        ],
        "seeds": ["place.ServiceProviderPlace", "place.sample.ToUpperPlace", "place.sample.TemplatePlace"],
        "configs": ["ToUpperPlace.cfg", "ToLowerPlace.cfg", "places.cfg", "emissary.admin.ClassNameInventory.cfg"],
        "tests": ["emissary.test.core.junit5.UnitTest", "emissary.test.core.junit5.ExtractionTest",
                  "emissary.test.core.junit5.RegressionTest", "emissary.test.core.junit5.IdentificationTest"],
    },
    {
        "id": "identify",
        "title": "Identify what a file is",
        "who": "Pipeline",
        "summary": "ID-stage places turn the UNKNOWN form into a real type using magic numbers, size, or custom engines.",
        "steps": [
            (E + "id.UnixFilePlace", "SERVICE_PROXY UNKNOWN; runs magic-number matching."),
            (E + "util.magic.MagicNumberFactory", "Loads the magic file rules."),
            (E + "id.IdPlace", "Base class for ID places (final-form handling)."),
            (E + "id.SizeIdPlace", "Labels payloads by size bucket."),
        ],
        "seeds": ["id.UnixFilePlace", "id.SizeIdPlace", "id.IdPlace"],
        "configs": ["UnixFilePlace.cfg", "SizeIdPlace.cfg"],
    },
    {
        "id": "kff",
        "title": "Skip known files (KFF)",
        "who": "Pipeline",
        "summary": "Hash payloads and check them against known-file lists (files or memcached) so known content "
                   "can be marked and skipped.",
        "steps": [
            (E + "place.KffHashPlace", "Hashes the payload."),
            (E + "kff.KffDataObjectHandler", "Computes hashes and records KFF results as parameters."),
            (E + "kff.KffChain", "Ordered list of known-file filters."),
            (E + "kff.KffFile", "Binary-searchable hash file filter."),
            (E + "kff.ChecksumCalculator", "MD5 / SHA / ssdeep fuzzy hashes."),
        ],
        "seeds": ["place.KffHashPlace", "kff.KffChain", "kff.KffMemcached"],
        "configs": ["KffHashPlace.cfg", "KffChain.cfg", "KffMemcached.cfg"],
    },
    {
        "id": "external-tools",
        "title": "Wrap external programs",
        "who": "Developer",
        "summary": "Run a native command-line tool as a processing step by writing the payload to a temp file, "
                   "running the command, and reading the result back.",
        "steps": [
            (E + "place.UnixCommandPlace", "Configure a command line; output replaces or joins the payload."),
            (E + "place.MultiFileUnixCommandPlace", "Variant where the tool emits many files (become attachments)."),
            (E + "util.shell.Executrix", "Temp files, command templating, process execution, timeouts."),
            (E + "util.shell.ProcessReader", "Drains stdout / stderr threads."),
        ],
        "seeds": ["place.UnixCommandPlace", "place.MultiFileUnixCommandPlace", "util.shell.Executrix"],
        "configs": [],
    },
    {
        "id": "grpc",
        "title": "Call external services over gRPC",
        "who": "Developer",
        "summary": "Newer extension point: a place that sends payloads to remote gRPC services with pooled "
                   "channels and retries. Only a sample implementation ships in this repository.",
        "steps": [
            (E + "grpc.sample.GrpcSamplePlace", "Example place."),
            (E + "grpc.GrpcRoutingPlace", "Routes calls to one of several configured endpoints."),
            (E + "grpc.invoker.GrpcInvoker", "Wraps stubs with retry and pooled channels."),
            (E + "grpc.pool.ConnectionFactory", "commons-pool2 channel pool with load-balancing policy."),
            (E + "grpc.retry.RetryHandler", "Retry policy for failed calls."),
        ],
        "seeds": ["grpc.GrpcConnectionPlace", "grpc.GrpcRoutingPlace", "grpc.sample.GrpcSamplePlace"],
        "configs": [],
    },
    {
        "id": "output",
        "title": "Write and roll output",
        "who": "Pipeline",
        "summary": "The IO stage formats finished payload families through pluggable filters and writes them to "
                   "rolling, crash-safe journaled files.",
        "steps": [
            (E + "output.DropOffPlace", "Collects the family and runs every configured OUTPUT_FILTER."),
            (E + "output.DropOffUtil", "Metadata helpers: file type, names, dates, parent/child ids."),
            (E + "output.filter.JsonOutputFilter", "JSON records per payload."),
            (E + "output.filter.AbstractRollableFilter", "Base for filters that write to rolling files."),
            (E + "output.roller.JournaledCoalescer", "Merges journaled parts into final output on roll."),
            (E + "output.roller.journal.JournaledChannelPool", "Pool of channels whose writes are journaled."),
            (E + "roll.RollManager", "Schedules time / size based rolls."),
        ],
        "seeds": ["output.DropOffPlace", "output.filter.JsonOutputFilter", "output.filter.XmlOutputFilter",
                  "roll.RollManager"],
        "configs": ["DropOffPlace.cfg", "DropOffUtil.cfg", "JsonOutputFilter.cfg", "RollManager.cfg"],
    },
    {
        "id": "watchdogs",
        "title": "Catch stuck or slow processing",
        "who": "Runtime",
        "summary": "Time every place call, interrupt agents that exceed limits, and optionally run Sentinel rules "
                   "that notify, dump threads or kill.",
        "steps": [
            (E + "core.MobileAgent", "atPlace() wraps each place call in a timer."),
            (E + "core.ResourceWatcher", "Tracks running timers; records per-place metrics."),
            (E + "core.TimedResource", "Interrupts the agent thread when the place's time limit passes."),
            (E + "core.sentinel.Sentinel", "Optional watchdog thread (ENABLED=false by default)."),
            (E + "core.sentinel.protocols.AgentProtocol", "Groups agents by place and evaluates rules."),
            (E + "core.sentinel.protocols.rules.AllMaxTime", "Rule: every agent in place X longer than N minutes."),
            (E + "core.sentinel.protocols.actions.Notify", "Default action: log a warning."),
        ],
        "seeds": ["core.ResourceWatcher", "core.sentinel.Sentinel"],
        "configs": ["Sentinel.cfg", "ProtocolSample.cfg"],
    },
    {
        "id": "payload",
        "title": "Represent and store payload data",
        "who": "Developer",
        "summary": "IBaseDataObject is the unit of work: bytes (in memory or behind a seekable channel), a stack of "
                   "current forms, parameters, and the transform history.",
        "steps": [
            (E + "core.IBaseDataObject", "The payload contract."),
            (E + "core.BaseDataObject", "Default implementation."),
            (E + "core.channels.SeekableByteChannelFactory", "Lazily opened data for large payloads."),
            (E + "core.channels.FileChannelFactory", "Backed by a file on disk."),
            (E + "core.TransformHistory", "Where the payload has been (used for loop detection)."),
            (E + "core.Family", "Naming for child payloads (attachments)."),
        ],
        "seeds": ["core.IBaseDataObject", "core.BaseDataObject", "core.channels.SeekableByteChannelFactory"],
        "configs": [],
    },
]
